name: 'Setup Jmeter'
description: 'Setup jmeter and jdk'


runs:
  using: 'composite'
  steps:
    - name: Install jmeter
      shell: bash
      run: |          
        curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install openjdk-8-jdk -y
        javac -version
        sudo wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar zxvf apache-jmeter-5.4.1.tgz
        mv apache-jmeter-5.4.1 jmeter-5.4.1
        jmeter-5.4.1/bin/jmeter -v
        cd jmeter-5.4.1/lib
        sudo wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar
        cd ext/
        sudo wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
        cd ..
        
        java  -jar cmdrunner-2.2.jar --tool org.jmeterplugins.repository.PluginManagerCMD install-all-except jpgc-hadoop,jpgc-oauth,ulp-jmeter-autocorrelator-plugin,ulp-jmeter-videostreaming-plugin,ulp-jmeter-gwt-plugin,tilln-iso8583
